### ISSUE TITLE
Doesn't work with latest cli

### ISSUE THREAD

**Issue by faboweb** [ascendancyy/vue-cli-plugin-stylelint#10]
```
> vue-cli-service serve

 ERROR  TypeError: Cannot destructure property `pluginOptions` of 'undefined' or 'null'.
TypeError: Cannot destructure property `pluginOptions` of 'undefined' or 'null'.
    at module.exports (C:\Users\Fabo\Documents\Entwicklung\lunie\node_modules\@ascendancyy\vue-cli-plugin-stylelint\index.js:7:66)
    at plugins.forEach (C:\Users\Fabo\Documents\Entwicklung\lunie\node_modules\@vue\cli-service\lib\Service.js:80:7)
    at Array.forEach (<anonymous>)
    at Service.init (C:\Users\Fabo\Documents\Entwicklung\lunie\node_modules\@vue\cli-service\lib\Service.js:79:18)
    at Service.run (C:\Users\Fabo\Documents\Entwicklung\lunie\node_modules\@vue\cli-service\lib\Service.js:206:10)
    at Object.<anonymous> (C:\Users\Fabo\Documents\Entwicklung\lunie\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

**Comment by PMK** [comment]
Add the following to your `package.json` to fix this issue:

```
"vue": {
    "pluginOptions": {
      "lintStyleOnBuild": false,
      "stylelint": {}
    }
}
```

**Comment by BoringDays** [comment]
I set rule stylelint-no-unsupported-browser-features's browser support to my own settings, then my vue cli 3 project fails to bootstraping. Any one knows why?

**Comment by RubenSibon** [comment]
Yes, that did the trick, but if you use `vue.config.js` add it there of course.
